"""added puuid to leagueuser schema

Revision ID: 212734082e99
Revises: d78bf2732340
Create Date: 2025-12-18 21:43:28.837004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212734082e99'
down_revision: Union[str, None] = 'd78bf2732340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'booster_card', ['id'])
    op.create_unique_constraint(None, 'booster_pack', ['id'])
    op.create_unique_constraint(None, 'cardbonuses', ['id'])
    op.create_unique_constraint(None, 'cards', ['id'])
    op.create_unique_constraint(None, 'guild', ['guild_id'])
    op.create_unique_constraint(None, 'images', ['label'])
    op.add_column('league_user', sa.Column('puuid', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'ownedcards', ['id'])
    op.create_unique_constraint(None, 'shop', ['id'])
    op.create_unique_constraint(None, 'user_account', ['id'])
    op.create_unique_constraint(None, 'votes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_constraint(None, 'shop', type_='unique')
    op.drop_constraint(None, 'ownedcards', type_='unique')
    op.drop_column('league_user', 'puuid')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'guild', type_='unique')
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_constraint(None, 'cardbonuses', type_='unique')
    op.drop_constraint(None, 'booster_pack', type_='unique')
    op.drop_constraint(None, 'booster_card', type_='unique')
    # ### end Alembic commands ###
