"""Added match_type to Match

Revision ID: 3e268b65623e
Revises: 212734082e99
Create Date: 2025-12-19 02:11:28.936438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e268b65623e'
down_revision: Union[str, None] = '212734082e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('match_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'match_type')
    # ### end Alembic commands ###
