"""re-run migration for verification

Revision ID: 55b493e65141
Revises: 57b10dfc53f1
Create Date: 2026-07-22 20:09:45.567904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b493e65141'
down_revision: Union[str, None] = '57b10dfc53f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_user', sa.Column('verification_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_user', 'verification_started_at')
    # ### end Alembic commands ###
