"""add league_user verification, fix shop date default

Revision ID: 57b10dfc53f1
Revises: 3e268b65623e
Create Date: 2026-07-16 21:58:29.904482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b10dfc53f1'
down_revision: Union[str, None] = '3e268b65623e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_user', sa.Column('verified', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('league_user', sa.Column('verification_icon_id', sa.Integer(), nullable=True))
    op.alter_column('shop', 'date_added',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'date_added',
               existing_type=sa.DATE(),
               server_default=sa.text("'2024-05-18'::date"),
               existing_nullable=False)
    op.drop_column('league_user', 'verification_icon_id')
    op.drop_column('league_user', 'verified')
    # ### end Alembic commands ###
