"""partial index guard verification

Revision ID: b78d2a3a1b0d
Revises: 57b10dfc53f1
Create Date: 2026-07-22 19:56:00.136838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78d2a3a1b0d'
down_revision: Union[str, None] = '57b10dfc53f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_league_user_verified_puuid', 'league_user', ['puuid'], unique=True, postgresql_where=sa.text('verified'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_league_user_verified_puuid', table_name='league_user', postgresql_where=sa.text('verified'))
    # ### end Alembic commands ###
